export function getAccounts(): { accounts: any[]; nextId: number };
export function addOrUpdateAccount(account: any): { accounts: any[]; nextId: number };
export function deleteAccount(id: string): { accounts: any[]; nextId: number };
export function getAutomation(accountId?: string): any;
export function getPlantingStrategy(accountId?: string): any;
export function getPreferredSeed(accountId?: string): number;
export function getIntervals(accountId?: string): any;
export function getFriendBlockLevel(accountId?: string): any;
export function getFriendQuietHours(accountId?: string): any;
export function getFriendBlacklist(accountId?: string): number[];
export function setFriendBlacklist(accountId: string, list: number[]): void;
export function getFriendCache(accountId?: string): any[];
export function setFriendCache(accountId: string, list: any[]): any[];
export function updateFriendCache(accountId: string, friends: any[]): any[];
export function getConfigSnapshot(accountId?: string): any;
export function applyConfigSnapshot(snapshot: any, options?: any): void;
export function setAutomation(key: string, value: unknown, accountId?: string): void;
export function isAutomationOn(key: string, accountId?: string): boolean;
export function getUI(): any;
export function setUITheme(theme: string): any;
export function getOfflineReminder(): any;
export function setOfflineReminder(cfg: any): any;
export function getQrLoginConfig(): any;
export function setQrLoginConfig(cfg: any): any;
export function getRuntimeClientConfig(): any;
export function setRuntimeClientConfig(cfg: any): any;
export function getAdminPasswordHash(): string;
export function setAdminPasswordHash(hash: string): void;
export function getDisablePasswordAuth(): boolean;
export function setDisablePasswordAuth(disabled: boolean): void;
export function getBagSeedPriority(accountId?: string): any;
